typography_spectrum: 1
color:
  brandColors:
    - '#ffffff'
    - '#4376cc'
    - '#afafaf'
    - '#000000'
    - '#ef9300'
  brandStrength: 0.25
  lightness: 0.8711048751138151
  saturation: 0.7118684456218034
  rhythmicContrast: 0.21207918203435838
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: lefant
cta:
  domain: null
  bucket: null
  version: null
favicon: null
description: "Happy hacker, functional programming and bayesian\_"
purpose: []
